# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_MCOM03_DMA32_BUS) += dma32-bus.o

obj-$(CONFIG_MCOM03R_OTP) += mcom03r-otp.o
mcom03r-otp-objs := common/mcom03-helpers.o mcom03r-otp/mcom03r-otp.o