# SPDX-License-Identifier: GPL-2.0

# MCom-03R
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-elvmc03smarc-r3.0.0-elvsmarccb-r3.3.0.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-elvmc03smarc-r3.0.0-elvsmarccb-r3.3.0-b156xw02-v0r.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-elvmc03smarc-r3.0.0-elvsmarccb-r3.3.0-m238hca-l3b.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-elvmc03smarc-r3.0.0-smarc-ukf-tfk-r1.1.1.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-ip-ku-m1-r1.0.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-ip-ku-m1-r1.1.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-ip-ku-m1-r1.0-b101uan01_hw_1a.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-ip-ku-m1-r1.0-claa101fp05xg.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-ip-ku-m1-r1.0-pm.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-skifmsb-v2.0-skifbs-v1.0.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-skifmsb-v2.0-skifbs-v1.0-rpi-dsi-7inch.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-skifmsb-v2.0-skifmp-v2.0.dtb
dtb-$(CONFIG_ARCH_MCOM03R) += mcom03r-skifmsb-v2.0-skifmp-v2.0-rpi-dsi-7inch.dtb

subdir-y += overlays
