/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright 2022 RnD Center "ELVEES", JSC
 *
 */

#ifndef DT_BINDINGS_MCOM03_CLOCK_H
#define DT_BINDINGS_MCOM03_CLOCK_H

/* CPU UCG */
#define CLK_CPU_UCG0_SYS 0
#define CLK_CPU_UCG0_CORE 1
#define CLK_CPU_UCG0_DBUS 2

/* SERVICE UCG */
#define CLK_SERVICE_UCG0_APB 0
#define CLK_SERVICE_UCG0_CORE 1
#define CLK_SERVICE_UCG0_QSPI0 2
#define CLK_SERVICE_UCG0_BPAM 3
#define CLK_SERVICE_UCG0_RISC0 4
#define CLK_SERVICE_UCG0_MFBSP0 5
#define CLK_SERVICE_UCG0_MFBSP1 6
#define CLK_SERVICE_UCG0_MAILBOX0 7
#define CLK_SERVICE_UCG0_PVTCTR 8
#define CLK_SERVICE_UCG0_I2C4 9
#define CLK_SERVICE_UCG0_TRNG 10
#define CLK_SERVICE_UCG0_SPIOTP 11
#define CLK_SERVICE_UCG0_I2C4_EXT 12
#define CLK_SERVICE_UCG0_QSPI0_EXT 13
#define CLK_SERVICE_UCG0_CLKOUT_EXT 14
#define CLK_SERVICE_UCG0_RISC0_TCK 15

/* SDR UCG0 */
#define CLK_SDR_UCG0_CFG 0
#define CLK_SDR_UCG0_EXT 1
#define CLK_SDR_UCG0_INT 2
#define CLK_SDR_UCG0_PCI 3
#define CLK_SDR_UCG0_VCUA 4
#define CLK_SDR_UCG0_ACC0 5
#define CLK_SDR_UCG0_ACC1 6
#define CLK_SDR_UCG0_ACC2 7
#define CLK_SDR_UCG0_AUX_PCI 8
#define CLK_SDR_UCG0_GNSS 9
#define CLK_SDR_UCG0_DFE_ALT 10
#define CLK_SDR_UCG0_VCU 11
#define CLK_SDR_UCG0_LVDS 12

/* SDR UCG_PCIE0, UCG_PCIE1 */
#define CLK_SDR_UCG_PCIE_REF_ALT 0

/* SDR UCG_JESD*_TX, UCG_JESD*_RX */
#define CLK_SDR_UCG_JESD_SAMPLE 1
#define CLK_SDR_UCG_JESD_CHARACTER 2

/* SDR N_DFE */
#define CLK_SDR_UCG_N_DFE_DFE_N 1

/* MEDIA UCG0 */
#define CLK_MEDIA_UCG0_SYSA 0
#define CLK_MEDIA_UCG0_ISP_SYS 1

/* MEDIA UCG1 */
#define CLK_MEDIA_UCG1_DISP_A 0
#define CLK_MEDIA_UCG1_DISP_M 1
#define CLK_MEDIA_UCG1_DISP_PXL 2

/* MEDIA UCG2 */
#define CLK_MEDIA_UCG2_GPU_SYS 0
#define CLK_MEDIA_UCG2_GPU_MEM 1
#define CLK_MEDIA_UCG2_GPU_CORE 2

/* MEDIA UCG3 */
#define CLK_MEDIA_UCG3_MIPI_RX_REF 0
#define CLK_MEDIA_UCG3_MIPI_RX0_CFG 1
#define CLK_MEDIA_UCG3_MIPI_RX1_CFG 2
#define CLK_MEDIA_UCG3_MIPI_TX_REF 3
#define CLK_MEDIA_UCG3_MIPI_TX_CFG 4
#define CLK_MEDIA_UCG3_CMOS0 5
#define CLK_MEDIA_UCG3_CMOS1 6
#define CLK_MEDIA_UCG3_MIPI_TXCLKESC 7
#define CLK_MEDIA_UCG3_VPU 8

/* DDR UCG0 */
#define CLK_DDR_UCG0_DDR0 0
#define CLK_DDR_UCG0_DDR0_X4 1
#define CLK_DDR_UCG0_DDR1 2
#define CLK_DDR_UCG0_DDR1_X4 3

/* DDR UCG1 */
#define CLK_DDR_UCG1_P 0
#define CLK_DDR_UCG1_A0 1
#define CLK_DDR_UCG1_A1 2
#define CLK_DDR_UCG1_A2 3
#define CLK_DDR_UCG1_A3 4
#define CLK_DDR_UCG1_A4 5
#define CLK_DDR_UCG1_A5 6
#define CLK_DDR_UCG1_A6 7
#define CLK_DDR_UCG1_A7 8
#define CLK_DDR_UCG1_A8 9
#define CLK_DDR_UCG1_A9 10
#define CLK_DDR_UCG1_A10 11

/* HSP UCG0 */
#define CLK_HSP_UCG0_SYS 0
#define CLK_HSP_UCG0_DMA 1
#define CLK_HSP_UCG0_CTR 2
#define CLK_HSP_UCG0_SPRAM 3
#define CLK_HSP_UCG0_EMAC0 4
#define CLK_HSP_UCG0_EMAC1 5
#define CLK_HSP_UCG0_USB0 6
#define CLK_HSP_UCG0_USB1 7
#define CLK_HSP_UCG0_NFC 8
#define CLK_HSP_UCG0_PDMA2 9
#define CLK_HSP_UCG0_SDMMC0 10
#define CLK_HSP_UCG0_SDMMC1 11
#define CLK_HSP_UCG0_QSPI 12

/* HSP UCG1 */
#define CLK_HSP_UCG1_SDMMC0_XIN 0
#define CLK_HSP_UCG1_SDMMC1_XIN 1
#define CLK_HSP_UCG1_NFC_FLASH 2
#define CLK_HSP_UCG1_QSPI_EXT 3
#define CLK_HSP_UCG1_UST 4

/* HSP UCG2 */
#define CLK_HSP_UCG2_EMAC0_1588 0
#define CLK_HSP_UCG2_EMAC0_RGMII_TXC 1
#define CLK_HSP_UCG2_EMAC1_1588 2
#define CLK_HSP_UCG2_EMAC1_RGMII_TXC 3

/* HSP UCG3 */
#define CLK_HSP_UCG3_USB0_REF_ALT 0
#define CLK_HSP_UCG3_USB0_SUSPEND 1
#define CLK_HSP_UCG3_USB1_REF_ALT 2
#define CLK_HSP_UCG3_USB1_SUSPEND 3

/* LSP0 UCG */
#define CLK_LSP0_UCG0_SYS 0
#define CLK_LSP0_UCG0_UART3 1
#define CLK_LSP0_UCG0_UART1 2
#define CLK_LSP0_UCG0_UART2 3
#define CLK_LSP0_UCG0_SPI0 4
#define CLK_LSP0_UCG0_I2C0 5
#define CLK_LSP0_UCG0_GPIO0_DB 6

/* LSP1 UCG */
#define CLK_LSP1_UCG0_SYS 0
#define CLK_LSP1_UCG0_I2C1 1
#define CLK_LSP1_UCG0_I2C2 2
#define CLK_LSP1_UCG0_I2C3 3
#define CLK_LSP1_UCG0_GPIO1_DB 4
#define CLK_LSP1_UCG0_SSI1 5
#define CLK_LSP1_UCG0_UART0 6
#define CLK_LSP1_UCG0_TIMERS0 7
#define CLK_LSP1_UCG0_PWM0 8
#define CLK_LSP1_UCG0_WDT1 9

/* LSP1 I2S_UCG */
#define CLK_LSP1_UCG_I2S_I2S0 0

#endif
