# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MCOM02) += \
        mcom02-bgproto.dtb \
        mcom02-ecam02dm-r1.1.dtb \
        mcom02-salute-el24d1-r1.3.dtb \
        mcom02-salute-el24d1-r1.4.dtb \
        mcom02-salute-el24d1-r1.5.dtb \
        mcom02-salute-el24d1-r1.5-rf2chan.dtb \
        mcom02-salute-el24d2-r1.1.dtb \
        mcom02-salute-el24d3-r1.1.dtb \
        mcom02-salute-el24pm1-r1.1-1.2-om1-r1.1-1.2.dtb \
        mcom02-salute-el24pm2-r1.0-1.1-om1-r1.2.dtb \
        mcom02-ukf-r0.dtb \
        mcom02-salute-el24pm2-r1.0-1.1-ukf-r1.0.dtb \
        mcom02-salute-el24pm2-r1.0-1.1-ukf-r1.1.dtb \
        mcom02-ipku-r1.1.dtb \
        mcom02-ipku-r2.0.dtb
